version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: perpus
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm install && until nc -z db 3306; do echo Waiting for MySQL...; sleep 2; done && npm run dev"

  db:
    image: mysql:8.0
    container_name: perpus_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: perpus
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./perpus.sql:/docker-entrypoint-initdb.d/perpus.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=root || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
